### ISSUE TITLE
1F09: System Synchronization

### ISSUE THREAD

**Issue by vdwulp** [Evsdd/The-Evohome-Protocol#1]
After reading the Wiki-page on command 1F09: System Synchronization, I would like to add the following:

1. The WRITE messages are send by the controller after binding a new device, always following command 0004 and followed by command 2309. I suppose the new device will not sleep until the first sync message is received.

2. The domain_id seems to be always FF for regular sync messages, always 00 when responding to a request and always F8 after binding a device.

3. In my installation the regular cycle time is 06E0 (176 seconds or 2m56s). I don't really understand (yet) what is meant by the cycle time being 'a multiple of two prime numbers', but does this value fit with this assumption?

I wonder if this is the right way to relay feedback on or additions to the Wiki. Please let me know if another channel is more appropriate.

**Comment by zxdavb** [comment]
First of all - thanks for contributing!

Presently, a big issue is the small number of people contributing to the wiki (and maybe even only one person for a particular packet), so things that may be true for them that do not hold true for all - we will learn more over time (see your point 3).

1 & 2 Good to have your insights, I will check/review and edit to the wiki.

3. Your value doesn't fit in with the prime number hypothesis. I think this point (see: https://www.newyorker.com/tech/elements/the-cicadas-love-affair-with-prime-numbers) is wrong so I will remove it.

I think reporting as issues is the way to go...

**Comment by vdwulp** [comment]
Thank you for your reaction to my input. I will report feedback on other pages of the wiki as issues too.
