### ISSUE TITLE
31D9/31DA: Non-evohome device, CVE-RF (ventilation)

### ISSUE THREAD

**Issue by vdwulp** [Evsdd/The-Evohome-Protocol#2]
Recently I started receiving messages from an unknown device, probably from a neighbor. It sends commands 31D9 and 31DA which are listed as unknown in the wiki.  Exactly the same messages are received quite frequently. Sharing these messages may help finding out more about them.
 
```
---  I --- 20:001414 --:------ 20:001414 31DA 029 00EF007FFFEFEF7FFF7FFF7FFF7FFFF000EF0251000000EFEF7FFF7FFF
---  I --- 20:001414 --:------ 20:001414 31D9 017 0006510020202020202020202020202000
```

I also received a message with command 10E0 (device info) from the same device, which reveals the device description **CVE-RF**. It seems to be a mechanical ventilation system.

```
---  I --- 20:001414 --:------ 20:001414 10E0 038   000001001B221201FEFFFFFFFFFF0C0507DF4356452D52460000000000000000000000000000
```

**Comment by zxdavb** [comment]
Hey, this is very interesting! Oddly, I have a ventilation system at home, so I already have the following in https://github.com/zxdavb/evohome_rf/tree/add_state (see below).

In my case, the devices are `30:` (the mechanical vent) and `32:` (Humidity sensor, Switch).

First thing I'm going to do is parse the payloads!

```python
@parser_decorator
def parser_31d9(payload, msg) -> Optional[dict]:
    assert len(payload) / 2 == 17  # usu: I 30:-->30:, with a seq#!
    assert payload[:2] == "21"  # domain
    assert payload[2:] == "00FF0000000000000000000000000000"

    return {
        "zone_idx" if int(payload[:2], 16) < 12 else "domain_id": _id(payload[:2]),
        "unknown_0": payload[2:],
    }


@parser_decorator
def parser_31da(payload, msg) -> Optional[dict]:  # UFH HCE80 (Nuaire humidity)
    assert len(payload) / 2 == 29  # usu: I CTL-->CTL
    assert payload[:2] == "21"  # domain

    return {
        "zone_idx" if int(payload[:2], 16) < 12 else "domain_id": _id(payload[:2]),
        "relative_humidity": _cent(payload[10:12]),
        "unknown_0": payload[2:10],
        "unknown_1": payload[12:],
    }
```

**Comment by zxdavb** [comment]
And decoded, they are:
```
20:001414 |  20:001414 |  I | message_31da     | 00EF0... || {'zone_idx': '00', 'relative_humidity': 2.39, 'unknown_0': 'EF007FFF', 'unknown_1': 'EF7FFF7FFF7FFF7FFFF000EF0251000000EFEF7FFF7FFF'}
20:001414 |  20:001414 |  I | message_31d9     | 00065... || {'zone_idx': '00', 'unknown_0': '06510020202020202020202020202000'}
20:001414 |  20:001414 |  I | device_info      | 00000... || {'description': 'CVE-RF', 'firmware': None, 'manufactured': '2015-05-12', 'unknown': '000001001B221201FEFF'}

**Comment by zxdavb** [comment]
And I think we've got this: https://github.com/Klusjesman/IthoEcoFanRFT

**Comment by zxdavb** [comment]
@gitkomodo Just to clarify something said above - some packets are 'known', just not documented in this wiki, yet. In addition, packets may be 'known', but not yet fully understood - the authorative reference might be [here](https://github.com/zxdavb/evohome_rf/blob/bleeding_edge/evohome/parsers.py) ~(this is missing only `0404` and `0006` parsers~.

I have been too busy on other projects to finish updating the wiki...

What code are you running to collect your packets? Is there any chance you could send me 24h of a packet log using https://github.com/zxdavb/evohome_rf? Especially of the packets to/from `20:` devices? There is another related packet, `31E0` (and possibly others).

If so, then I can suggest the **bleeding_edge** branch.  If you're collecting them via another tool, I would still like to see them - maybe you could reformat them into the 'standard' format:
```
2020-05-13T01:16:45.808427 095 RQ --- 18:013393 01:145038 --:------ 1F09 001 00
```
... or as near as you can get?

**Comment by zxdavb** [comment]
Closing - these packets (`31D9`, `31DA`) are better understood, but still a WIP.
