### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by pdbayes** [Evsdd/The-Evohome-Protocol#7]
Hi

Do you know what the _flags_n in the data field means. Seems to always have a value of FF which seems like it is likely to be an on off kind of thing, but I never see the 00 equivalent
Thanks

**Comment by zxdavb** [comment]
As the understanding of the RAMSES II protocol has evolved, this repository has not been kept up to date (my fault).

IMHO, the authoritative source of all known understanding in this repo: [here](https://github.com/zxdavb/ramses_rf/blob/master/ramses_rf/protocol/parsers.py) and also [here](https://github.com/zxdavb/ramses_rf/blob/master/ramses_rf/protocol/ramses.py). 

The above is all the latest data I have - it is a much larger corpus of knowledge than this repo, and you should be looking there.

If you require more info, you will have to provide more data - starting with which specific command class (packet code) you are interested in.
